[tool.pylint.MESSAGE_CONTROL]
disable = """
    inconsistent-return-statements,
    missing-function-docstring,
    relative-beyond-top-level,
    keyword-arg-before-vararg,
    missing-module-docstring,
    useless-super-delegation,
    consider-using-enumerate,
    consider-using-f-string,
    missing-class-docstring,
    unused-wildcard-import,
    global-at-module-level,
    too-many-nested-blocks,
    too-few-public-methods,
    invalid-sequence-index,
    unspecified-encoding,
    wrong-import-order,
    too-many-ancestors,
    too-many-branches,
    redefined-builtin,
    consider-using-in,
    global-statement,
    missing-timeout,
    too-many-locals,
    wildcard-import,
    no-else-return,
    duplicate-code,
    no-else-raise,
    line-too-long,
    invalid-name,
    import-error,
    no-member,
    fixme,
"""